const languages = [
{ code: '', name: 'Select Language' },
{ code:"af",name:"Afrikaans"},
{ code:"sq",name:"Albanian"},
{ code:"ar",name:"Arabic"},
{ code:"hy",name:"Armenian"},
{ code:"as",name:"Assamese"},
{ code:"az",name:"Azerbaijani"},
{ code:"eu",name:"Basque"},
{ code:"bel",name:"Belarusian"},
{ code:"bn-BD",name:"Bengali (Bangladesh)"},
{ code:"bs-BA",name:"Bosnian"},
{ code:"bg-BG",name:"Bulgarian"},
{ code:"ca",name:"Catalan"},
{ code:"ceb",name:"Cebuano"},
{ code:"zh-CN",name:"Chinese (China)"},
{ code:"zh-HK",name:"Chinese (Hong Kong)"},
{ code:"zh-Hans",name:"Chinese (Simplified)"},
{ code:"zh-TW",name:"Chinese (Taiwan)"},
{ code:"zh-Hant",name:"Chinese (Traditional)"},
{ code:"hr",name:"Croatian"},
{ code:"cs",name:"Czech"},
{ code:"cs-CZ",name:"Czech (Czechia)"},
{ code:"da-DK",name:"Danish"},
{ code:"nl",name:"Dutch"},
{ code:"nl-BE",name:"Dutch (Belgium)"},
{ code:"nl-NL",name:"Dutch (Netherlands)"},
{ code:"dzo",name:"Dzongkha"},
{ code:"en",name:"English"},
{ code:"en-AU",name:"English (Australia)"},
{ code:"en-BE",name:"English (Belgium)"},
{ code:"en-CA",name:"English (Canada)"},
{ code:"en-CN",name:"English (China)"},
{ code:"en-HK",name:"English (Hong Kong)"},
{ code:"en-IN",name:"English (India)"},
{ code:"en-ID",name:"English (Indonesia)"},
{ code:"en-IE",name:"English (Ireland)"},
{ code:"en-MY",name:"English (Malaysia)"},
{ code:"en-MM",name:"English (Myanmar)"},
{ code:"en-NL",name:"English (Netherlands)"},
{ code:"en-NZ",name:"English (New Zealand)"},
{ code:"en-PH",name:"English (Philippines)"},
{ code:"en-RO",name:"English (Romania)"},
{ code:"en-SG",name:"English (Singapore)"},
{ code:"en-ZA",name:"English (South Africa)"},
{ code:"en-CH",name:"English (Switzerland)"},
{ code:"en-TH",name:"English (Thailand)"},
{ code:"en-GB",name:"English (UK)"},
{ code:"en-AE",name:"English (United Arab Emirates)"},
{ code:"en-US",name:"English (United States)"},
{ code:"eo",name:"Esperanto"},
{ code:"et",name:"Estonian"},
{ code:"fi",name:"Finnish"},
{ code:"fr",name:"French"},
{ code:"fr-BE",name:"French (Belgium)"},
{ code:"fr-CA",name:"French (Canada)"},
{ code:"fr-FR",name:"French (France)"},
{ code:"fr-LU",name:"French (Luxembourg)"},
{ code:"fr-CH",name:"French (Switzerland)"},
{ code:"fur",name:"Friulian"},
{ code:"gl-ES",name:"Galician"},
{ code:"ka-GE",name:"Georgian"},
{ code:"de-AT",name:"German (Austria)"},
{ code:"de",name:"German (DE)"},
{ code:"de-DE",name:"German (Germany)"},
{ code:"de-CH",name:"German (Switzerland)"},
{ code:"el",name:"Greek"},
{ code:"gu",name:"Gujarati"},
{ code:"haz",name:"Hazaragi"},
{ code:"he-IL",name:"Hebrew"},
{ code:"hi-IN",name:"Hindi"},
{ code:"hu-HU",name:"Hungarian"},
{ code:"is-IS",name:"Icelandic"},
{ code:"id-ID",name:"Indonesian"},
{ code:"it",name:"Italian"},
{ code:"it-IT",name:"Italian (Italy)"},
{ code:"ja",name:"Japanese"},
{ code:"jv-ID",name:"Javanese"},
{ code:"kab",name:"Kabyle"},
{ code:"kn",name:"Kannada"},
{ code:"kk",name:"Kazakh"},
{ code:"km",name:"Khmer"},
{ code:"ko-KR",name:"Korean"},
{ code:"ckb",name:"Kurdish (Sorani)"},
{ code:"lo",name:"Lao"},
{ code:"lv",name:"Latvian"},
{ code:"lt-LT",name:"Lithuanian"},
{ code:"mk-MK",name:"Macedonian"},
{ code:"ms-MY",name:"Malay"},
{ code:"ml-IN",name:"Malayalam"},
{ code:"mr",name:"Marathi"},
{ code:"mn",name:"Mongolian"},
{ code:"ary",name:"Moroccan Arabic"},
{ code:"my-MM",name:"Myanmar (Burmese)"},
{ code:"ne-NP",name:"Nepali"},
{ code:"no-NO",name:"Norwegian"},
{ code:"nb-NO",name:"Norwegian (Bokm책l)"},
{ code:"no",name:"Norwegian (Default)"},
{ code:"nn-NO",name:"Norwegian (Nynorsk)"},
{ code:"oci",name:"Occitan"},
{ code:"ps",name:"Pashto"},
{ code:"fa-IR",name:"Persian"},
{ code:"pl",name:"Polish"},
{ code:"pl-PL",name:"Polish (Poland)"},
{ code:"pt",name:"Portuguese"},
{ code:"pt-AO",name:"Portuguese (Angola)"},
{ code:"pt-BR",name:"Portuguese (Brazil)"},
{ code:"pt-PT",name:"Portuguese (Portugal)"},
{ code:"pa-IN",name:"Punjabi"},
{ code:"rhg",name:"Rohingya"},
{ code:"ro-RO",name:"Romanian"},
{ code:"ru",name:"Russian"},
{ code:"ru-RU",name:"Russian (Russia)"},
{ code:"sah",name:"Sakha"},
{ code:"skr",name:"Saraiki"},
{ code:"gd",name:"Scottish Gaelic"},
{ code:"sr-RS",name:"Serbian"},
{ code:"szl",name:"Silesian"},
{ code:"si-LK",name:"Sinhala"},
{ code:"sk-SK",name:"Slovak"},
{ code:"sl-SI",name:"Slovenian"},
{ code:"azb",name:"South Azerbaijani"},
{ code:"es",name:"Spanish"},
{ code:"es-AR",name:"Spanish (Argentina)"},
{ code:"es-CL",name:"Spanish (Chile)"},
{ code:"es-CO",name:"Spanish (Colombia)"},
{ code:"es-CR",name:"Spanish (Costa Rica)"},
{ code:"es-GT",name:"Spanish (Guatemala)"},
{ code:"es-MX",name:"Spanish (Mexico)"},
{ code:"es-PE",name:"Spanish (Peru)"},
{ code:"es-ES",name:"Spanish (Spain)"},
{ code:"es-VE",name:"Spanish (Venezuela)"},
{ code:"sv",name:"Swedish"},
{ code:"sv-SE",name:"Swedish (Sweden)"},
{ code:"tl",name:"Tagalog"},
{ code:"tah",name:"Tahitian"},
{ code:"tg",name:"Tajik"},
{ code:"ta-IN",name:"Tamil"},
{ code:"tt-RU",name:"Tatar"},
{ code:"te",name:"Telugu"},
{ code:"th",name:"Thai"},
{ code:"bo",name:"Tibetan"},
{ code:"tr",name:"Turkish"},
{ code:"tr-TR",name:"Turkish (Turkey)"},
{ code:"tk",name:"Turkmen"},
{ code:"ug-CN",name:"Uighur"},
{ code:"uk",name:"Ukrainian"},
{ code:"ur",name:"Urdu"},
{ code:"uz",name:"Uzbek"},
{ code:"uz-UZ",name:"Uzbek (Uzbekistan)"},
{ code:"vi",name:"Vietnamese"},
{ code:"cy",name:"Welsh"},


  // ...更多语言
];

export default languages;


